### ISSUE TITLE
Manual's page 93 is flipped

### ISSUE THREAD

**Issue by HitLuca** [MasturMynd/Pandoras_Box#15]
Looks like the page 93 of the assembly manual is flipped horizontally

**Comment by LillianaMirrors** [comment]
Known issue, will be fixed in the next revision, coming soonTM

**Comment by MasturMynd** [comment]
Reopening as this doesn't appear to have been resolved yet.

**Comment by MasturMynd** [comment]
Actually, upon further inspection, this is actually one of the "easter eggs" that Lilli and I had conspired on. There are a few other pages that are the same =)
