### ISSUE TITLE
Pg 55 has extrusion labeled G, should be F

### ISSUE THREAD

**Issue by ReillyBex** [MasturMynd/Pandoras_Box#17]
Shows “G” extrusion being affixed to gantry brace on page 55 of the current manual. Pretty sure it should be “F”, but I might just be tripping.

**Comment by MasturMynd** [comment]
The "G Extrusion" wouldn't need tapped ends. It doesn't look like there's a callout for this and I, sadly, don't have files to edit this manual =/
