### ISSUE TITLE
Poor probe accuracy at max Y

### ISSUE THREAD

**Issue by MasturMynd** [MasturMynd/Pandoras_Box#8]
Due to the asymmetric belt mounting / tensioning between the front and rear z set, probing near the rear of the bed is known to be inconsistent without significant attention to detail.

**Comment by NeighNeighNeigh** [comment]
I'm very close to committing to building a Pandora's Box (instead of my stock V0.2 kit) – but hoping you might elaborate on the implications of this issue? Should I be concerned?

**Comment by MasturMynd** [comment]
> I'm very close to committing to building a Pandora's Box (instead of my stock V0.2 kit) – but hoping you might elaborate on the implications of this issue? Should I be concerned?

This issue has been addressed via a mod that has been tested with a number of builds from the DoomCube discord server. I'll be publishing said mod shortly!
